# Travis CI script
language: c

cache: ccache

os:
- linux
- osx
arch:
  - amd64
  - ppc64le
sudo: false

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    - CI_TIME=true
    - CI_TRACE=false
    - CI_CONFIG_QUIET=true
  matrix:
    - BUILD_TYPE=default

script:
- ./ci_build.sh
